# Testing deque-ndarray compatibility

In [2]:
import numpy as np
from collections import deque

In [3]:
h=np.zeros((7,3,3))
print(h)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [31]:
i = deque(maxlen=7)
i.appendleft(np.eye((3))) # latest first
i.appendleft(np.ones((3,3)))
i.appendleft(np.ones((3,3))*2)
print(i)

deque([array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]]), array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])], maxlen=7)


In [39]:
h[:len(i)]=i
print(h)
print(h.size)
print(h.shape)
print(h[:2])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
63
(7, 3, 3)
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
j = np.zeros((7,4))
print(j)
print(j.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
28


In [32]:
k = deque(maxlen=7)
k.appendleft([5,5,5,16])
k.appendleft([4,6,3,18])
k.appendleft([4,7,2,20])
k.appendleft(np.hstack((np.array([0,0,0]), 23)))
print(k)

deque([array([ 0,  0,  0, 23]), [4, 7, 2, 20], [4, 6, 3, 18], [5, 5, 5, 16]], maxlen=7)


In [33]:
j[:len(k)]=k
print(j)

[[ 0.  0.  0. 23.]
 [ 4.  7.  2. 20.]
 [ 4.  6.  3. 18.]
 [ 5.  5.  5. 16.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [26]:
l = np.ravel(j)
print(l)
o = l.reshape((j.shape[0], j.shape[1]))
print(o)
o[:]=0
print(o)

[ 4.  7.  2. 20.  4.  6.  3. 18.  5.  5.  5. 16.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 4.  7.  2. 20.]
 [ 4.  6.  3. 18.]
 [ 5.  5.  5. 16.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
time = 16
mask = j[:,3]==time
print(mask)

[False False  True False False False False]


In [11]:
print(h[mask][0])
print(j[mask][0][:-1])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[5. 5. 5.]


In [13]:
T=np.zeros((3,1))
print(T)

[[0.]
 [0.]
 [0.]]


In [14]:
print(T.T)

[[0. 0. 0.]]


In [24]:
T=np.array([0, 0, 0])
print(T)
print(T.T)
print(T.T.shape)
T=np.array([np.array([0,0,0])]).T
print(T)
print(T.shape)

[0 0 0]
[0 0 0]
(3,)
[[0]
 [0]
 [0]]
(3, 1)


In [37]:
p=np.ones((4,4))
print(p)
q = p[:3,3]
print(q)
print(q.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1.]
(3,)
