# Testing deque-ndarray compatibility

In [32]:
import numpy as np
from collections import deque

In [33]:
h=np.zeros((7,3,3))
print(h)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [34]:
i = deque(maxlen=7)
i.appendleft(np.eye((3))) # latest first
i.appendleft(np.ones((3,3)))
i.appendleft(np.ones((3,3))*2)
print(i)

deque([array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]]), array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])], maxlen=7)


In [35]:
h[:len(i)]=i
print(h)
print(h.size)
print(h.shape)
print(h[:2])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
63
(7, 3, 3)
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [36]:
j = np.zeros((7,4))
print(j)
print(j.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
28


In [37]:
k = deque(maxlen=7)
k.appendleft([5,5,5,16])
k.appendleft([4,6,3,18])
k.appendleft([4,7,2,20])
k.appendleft(np.hstack((np.array([0,0,0]), 23)))
print(k)
j[:len(k)]=k
print(j)

deque([array([ 0,  0,  0, 23]), [4, 7, 2, 20], [4, 6, 3, 18], [5, 5, 5, 16]], maxlen=7)
[[ 0.  0.  0. 23.]
 [ 4.  7.  2. 20.]
 [ 4.  6.  3. 18.]
 [ 5.  5.  5. 16.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


[[ 0.  0.  0. 23.]
 [ 4.  7.  2. 20.]
 [ 4.  6.  3. 18.]
 [ 5.  5.  5. 16.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [38]:
l = np.ravel(j)
print(l)
o = l.copy().reshape((j.shape[0], j.shape[1]))
print(o)
o[:]=0
print(o)

[ 0.  0.  0. 23.  4.  7.  2. 20.  4.  6.  3. 18.  5.  5.  5. 16.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0. 23.]
 [ 4.  7.  2. 20.]
 [ 4.  6.  3. 18.]
 [ 5.  5.  5. 16.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
time = 16.0
mask = j[:,3]==time
print(mask)

[False False False  True False False False]


In [40]:
print(h[mask][0])
print(j[mask][0][:-1])

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[5. 5. 5.]


In [41]:
T=np.zeros((3,1))
print(T)

[[0.]
 [0.]
 [0.]]


In [42]:
print(T.T)

[[0. 0. 0.]]


In [43]:
T=np.array([0, 0, 0])
print(T)
print(T.T)
print(T.T.shape)
T=np.array([np.array([0,0,0])]).T
print(T)
print(T.shape)

[0 0 0]
[0 0 0]
(3,)
[[0]
 [0]
 [0]]
(3, 1)


In [44]:
p=np.ones((4,4))
print(p)
q = p[:3,3]
print(q)
print(q.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1.]
(3,)


In [45]:
h = np.zeros(63).astype(int)
print(h)
j = h.reshape((7,3,3))
print(j)
k = deque(maxlen=7)
k.appendleft(np.array([ [ 0,  0, -1],
                        [ 0,  1,  0],
                        [ 1,  0,  0] ]).copy().T)
print(k)
j[:len(k)] = k
print(j)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
deque([array([[ 0,  0,  1],
       [ 0,  1,  0],
       [-1,  0,  0]])], maxlen=7)
[[[ 0  0  1]
  [ 0  1  0]
  [-1  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


In [46]:
o = np.ones([3,3])
print(o)
p = o*0.9
print(p)
l = abs(o-p)
print(l)
mask = np.any(l>0.05)
print(mask)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.9 0.9 0.9]
 [0.9 0.9 0.9]
 [0.9 0.9 0.9]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
True


In [47]:
k = deque(maxlen=7)
k.appendleft([5,5,5,16])
k.appendleft([4,6,3,21])
k.appendleft([4,7,2,37])
k.appendleft(np.hstack((np.array([0,0,0]), 44)))
print(k)
j = np.zeros((7,4))
print(j)
print(j.size)
j[:len(k)]=k
print(j)

deque([array([ 0,  0,  0, 44]), [4, 7, 2, 37], [4, 6, 3, 21], [5, 5, 5, 16]], maxlen=7)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
28
[[ 0.  0.  0. 44.]
 [ 4.  7.  2. 37.]
 [ 4.  6.  3. 21.]
 [ 5.  5.  5. 16.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [48]:
time = 50
timediff = abs(j[:,3]-time)
print(timediff)
m = np.argmin(timediff)
n = j[m]
print(n)

[ 6. 13. 29. 34. 50. 50. 50.]
[ 0.  0.  0. 44.]


In [49]:
h = np.zeros(63).astype(int)
print(h)
j = h.reshape((7,3,3))
print(j)
k = deque(maxlen=7)
k.appendleft(np.array([ [ 0,  0, -1],
                        [ 0,  1,  0],
                        [ 1,  0,  0] ]).copy().T)
print(k)
j[:len(k)] = k
print(j)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
deque([array([[ 0,  0,  1],
       [ 0,  1,  0],
       [-1,  0,  0]])], maxlen=7)
[[[ 0  0  1]
  [ 0  1  0]
  [-1  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]


In [50]:
print(j[m])

[[ 0  0  1]
 [ 0  1  0]
 [-1  0  0]]
