# Testing deque-ndarray compatibility

In [12]:
import numpy as np
from collections import deque

In [13]:
h=np.zeros((7,3,3))
print(h)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [14]:
i = deque(maxlen=7)
i.appendleft(np.eye((3))) # latest first
i.appendleft(np.ones((3,3)))
i.appendleft(np.ones((3,3))*2)
print(i)

deque([array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]]), array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]]), array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])], maxlen=7)


In [15]:
h[:len(i)]=i
print(h)
print(h.size)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
63


In [21]:
j = np.zeros((7,4))
print(j)
print(j.size)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
28


In [17]:
k = deque(maxlen=7)
k.appendleft([5,5,5,16])
k.appendleft([4,6,3,18])
k.appendleft([4,7,2,20])
print(k)

deque([[4, 7, 2, 20], [4, 6, 3, 18], [5, 5, 5, 16]], maxlen=7)


In [24]:
j[:len(k)]=k
print(j)

[[ 4.  7.  2. 20.]
 [ 4.  6.  3. 18.]
 [ 5.  5.  5. 16.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [26]:
l = np.ravel(j)
print(l)
l.reshape((j.shape[0], j.shape[1]))

[ 4.  7.  2. 20.  4.  6.  3. 18.  5.  5.  5. 16.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


array([[ 4.,  7.,  2., 20.],
       [ 4.,  6.,  3., 18.],
       [ 5.,  5.,  5., 16.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [19]:
time = 16
mask = j[:,3]==time
print(mask)

[False False  True False False False False]


In [20]:
print(h[mask][0])
print(j[mask][0][:-1])

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[5. 5. 5.]
